CC=gcc

prob2: prob2.c
	$(CC) -o prob2 prob2.c

prob3: prob3.c
	$(CC) -o prob3 prob3.c

prob4: prob4.c
	$(CC) -o prob4 prob4.c

prob5: prob5.c
	$(CC) -o prob5 prob5.c

prob6: prob6.c
	$(CC) -o prob6 prob6.c
	
clean:
	rm *.o temp


